---
- name: Base configuration
  hosts: all
  become: true
  tasks:
  - name: Time Zone
    timezone:
      name: CET
  - name: ntp installed
    package:
      name: ntp
  - name: ntp enabled
    when: not ansible_distribution == "Debian"
    service:
      name: ntpd
      enabled: true
      state: started
  - name: Names en /etc/hosts
    blockinfile:
      path: /etc/hosts
      block: |
        192.168.1.10 nfs
        192.168.1.11 nfs1
        192.168.1.12 nfs2
        192.168.1.20 iscsi
        192.168.1.100 client

# https://www.tecmint.com/setup-iscsi-target-and-initiator-on-debian-9/
- name: iSCSI Target
  hosts: iscsi
  become: true
  tasks:
  - name: LVM software
    package:
      name: lvm2
  - name: Volume Group
    lvg:
      vg: datavg
      pvs: /dev/sdb
  - name: Logical Volume
    lvol:
      lv: datalv
      size: 100%VG
      vg: datavg
  - name: iSCSI software
    package:
      name: tgt
  - name: iSCSI configuration
    copy:
      src: data_iscsi.conf
      dest: /etc/tgt/conf.d/
    register: config
  - name: Reload iSCSI service
    when: config.changed
    service:
      name: tgt
      state: restarted

- name: iSCSI Initiators
  hosts:
  - nfs1
  - nfs2
  become: true
  tasks:
  - name: iSCSI software
    package:
      name: open-iscsi
  - name: Check if already detected
    stat:
      path: '/etc/iscsi/nodes/iqn.2018-08.es.raulpedroche:lun1/192.168.50.20,3260,1/default'
    register: default
  - name: Discovery
    when: not default.stat.exists
    command: iscsiadm -m discovery -t st -p 192.168.50.20
  - name: Authentication
    blockinfile:
      create: no
      path: '/etc/iscsi/nodes/iqn.2018-08.es.raulpedroche:lun1/192.168.50.20,3260,1/default'
      block: |
        node.session.auth.method = CHAP
        node.session.auth.username = nfs-iscsi-user
        node.session.auth.password = secret0
        node.session.auth.username_in = debian-iscsi-target
        node.session.auth.password_in = s3cr3to
    register: auth
  - name: Autostart
    lineinfile:
      create: no
      path: '/etc/iscsi/nodes/iqn.2018-08.es.raulpedroche:lun1/192.168.50.20,3260,1/default'
      regexp: '^node\.startup'
      line: 'node.startup = automatic'
  - name: Restart iSCSI initiator
    when: auth.changed
    service:
      name: open-iscsi
      state: restarted

# http://realtechtalk.com/configuring_ocfs2_clustered_file_system_on_debian_based_linux_including_ubuntu_and_kubuntu-109-articles
- name: OCFS cluster
  hosts:
  - nfs1
  - nfs2
  become: true
  tasks:
  - name: OCFS2 software
    apt:
      name: ocfs2-tools
  - name: Enable O2CB
    lineinfile:
      create: no
      path: /etc/default/o2cb
      regexp: '^O2CB_ENABLED'
      line: 'O2CB_ENABLED=true'
  - name: OCFS2 configuration directory
    file:
      state: directory
      path: /etc/ocfs2
  - name: OCFS2 cluster.conf
    copy:
      src: cluster.conf
      dest: /etc/ocfs2/
    register: cluster_conf
  - name: Restart OCFS2 service
    when: cluster_conf.changed
    service:
      name: o2cb
      state: restarted

- name: Create OCFS2 file system
  hosts: nfs1
  become: true
  tasks:
  - name: Check if /root/.creado_ocfs2 exists
    stat:
      path: /root/.creado_ocfs2
    register: creado
  - name: Check if lost+found exists
    stat:
      path: /srv/nfs4/data/lost+found
    register: lost_found
  - name: Create file system
    when: not creado.stat.exists and not lost_found.stat.exists
    command: 'mkfs.ocfs2 -b 4k -C 32K -L Datos -N 4 /dev/sdb'
  - name: /root/.creado_ocfs2 present
    lineinfile:
      create: yes
      path: /root/.creado_ocfs2
      line: "El sistema de archivos está creado"

- name: Mount OCFS2 file system
  hosts:
  - nfs1
  - nfs2
  become: true
  tasks:
  - name: Mount point
    file:
      path: /srv/nfs4/data
      state: directory
  - name: Mount file system
    mount:
      fstype: ocfs2
      path: /srv/nfs4/data
      src: /dev/sdb
      state: mounted

- name: NFSv4 export
  hosts:
  - nfs1
  - nfs2
  become: true
  tasks:
  - name: NFS software
    apt:
      name: nfs-kernel-server
  - name: idmapd enabled
    lineinfile:
      path: /etc/default/nfs-common
      regexp: '^NEED_IDMAPD'
      line: 'NEED_IDMAPD=true'
  - name: /etc/exports
    copy:
     src: exports
     dest: /etc/exports
    register: exports
  - name: Restart NFS
    when: exports.changed
    service:
      name: nfs-server
      state: restarted
